std = "lua51"
max_line_length = 180
exclude_files = {
    "Libs/",
    ".git/",
}
globals = {
    "LibStub",
    "CreateFrame",
    "AuctionHouseFrame",
    "AuctionHouseUtil",
    "Enum",
    "C_AuctionHouse",
    "C_Item",
    "C_Timer",
    "C_CurrencyInfo",
    "GameTooltip",
    "GameTooltip_Hide",
    "StaticPopupDialogs",
    "StaticPopup_Show",
    "GetCoinTextureString",
    "GetBuildInfo",
    "WOW_PROJECT_ID",
    "WOW_PROJECT_MAINLINE",
    "Auctionator",
    "DisenchantBuddy",
    "Arbitrage_Profile",
    "assert.spy",
    "assert.are_same",
    "assert.is_nil",
    "describe",
    "before_each",
    "it",
    "spy",
}
